version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: telq_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: telq_web_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # --- [PERBAIKAN DISINI] ---
      # Ubah nama file sesuai dengan file asli kamu (.pkl)
      # Pastikan nama depannya (telq_model) juga sesuai dengan file kamu
      - ML_MODEL_PATH=backend/ml/output/XGBoost_v3_25Nov2025/xgb_telco_optimal_v1.pkl
      - ML_COLUMNS_PATH=backend/ml/output/XGBoost_v3_25Nov2025/xgb_feature_columns_v1.pkl

volumes:
  postgres_data: